spring:
  datasource:
    url: jdbc:mysql://192.168.0.135:3306/xcwl_b2c_gateway?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 1Mtg_izQtZow
eureka:
  instance:
    prefer-ip-address: true
  server:
    address: 192.168.0.135:8761
    user: xcwl
    password: 123456
  client:
    enabled: true
    service-url:
      defaultZone: http://${eureka.server.user}:${eureka.server.password}@${eureka.server.address}/eureka
